import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import './AboutPage.css'
import RequestCallForm from '../components/RequestCallForm'
import ReviewSlider from '../components/ReviewSlider'
import { TESTIMONIALS } from '../data/testimonials'
export const ABOUT_TITLE='About Us | Virtual Assistant Medical'
export const ABOUT_DESCRIPTION='Meet Virtual Assistant Medical. Learn about our mission, vision, and approach to remote scheduling, patient coordination, and healthcare administration.'
const base='https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site'
const schema={'@context':'https://schema.org','@type':'AboutPage',name:ABOUT_TITLE,description:ABOUT_DESCRIPTION,url:base+'/about-us/',about:{'@type':'Organization',name:'Virtual Assistant Medical',alternateName:'VAM',url:base}}
function AboutIcon({kind=0}:{kind?:number}){const paths=['M12 3v18 M3 12h18 M8 3H4v4 M16 3h4v4 M4 17v4h4 M20 17v4h-4','M12 3l9 5-9 5-9-5z M5 12v6l7 4 7-4v-6','M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6','M4 4h16v12H9l-5 4z M8 8h8 M8 12h5','M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 15l3 3 5-5','M9 3h6v4H9z M9 5H5v16h14V5h-4 M8 11h8 M8 15h8 M8 18h4'];return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind%paths.length]}/></svg>}
const values=[{title:'Care in every conversation',text:'Patient calls and messages deserve the same respect as an in-person visit. We value clear language, attentive listening, and thoughtful follow-through.',kind:3},{title:'Responsibility in every task',text:'Defined ownership, accurate information, and clear handoffs keep everyday work moving. Questions and exceptions should reach the right person.',kind:5},{title:'Privacy by design',text:'Patient information belongs within approved systems and access boundaries. Confidentiality is a responsibility that shapes the way support is planned.',kind:2},{title:'Partnership over a fixed formula',text:'Every practice has its own priorities. We value feedback and practical adjustments that make remote support useful to your team.',kind:0}]
const services=[{title:'Reception & patient communication',text:'Support incoming calls, appointment requests, reminders, and patient follow-ups with a consistent, welcoming front-desk experience.',to:'/virtual-medical-receptionist/',kind:3},{title:'Documentation & office coordination',text:'Bring structure to records preparation, documentation support, inboxes, and day-to-day administrative tasks under your team’s direction.',to:'/services',kind:5},{title:'Billing & practice support',text:'Coordinate billing-related administration, insurance information, and outstanding follow-ups alongside your existing practice team.',to:'/services',kind:4}]
const reasons=[['Built around healthcare','Support focuses on the practical needs of a medical office, from patient communication to appointment coordination and documentation.'],['Aligned with your systems','Plan responsibilities around your EHR, scheduling software, approved access, and existing processes. Your workflow guides the setup.'],['Clear roles and handoffs','Agree on call scripts, task ownership, and escalation rules. Administrative support stays connected to the people responsible for care.'],['Flexible priorities','Start with the work that needs attention most. Review coverage and responsibilities as patient volume or practice needs change.'],['More room for your on-site team','Remote support helps distribute routine work so your internal staff can give attention to patients and tasks that require them in person.'],['Communication that keeps you informed','Use agreed updates and feedback to keep priorities visible, address issues, and improve how your team and VAM work together.']]
function AnimatedNumber({value}:{value:number}){
 const ref=useRef<HTMLSpanElement>(null),[shown,setShown]=useState(value)
 useEffect(()=>{const el=ref.current;if(!el||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)return;observer.disconnect();const start=performance.now();setShown(0);function tick(now:number){const p=Math.min((now-start)/1400,1);setShown(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick)},{threshold:.4});observer.observe(el);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value])
 return <span ref={ref} aria-label={String(value)}><span aria-hidden="true">{shown}</span></span>
}
export default function AboutPage(){
 useEffect(()=>{const tags=Array.from(document.querySelectorAll<HTMLMetaElement>('meta[name="robots"]'));const old=tags.map(t=>t.content);tags.forEach(t=>t.content='index, follow');return()=>tags.forEach((t,i)=>t.content=old[i])},[])
 return <div className="vam-about"><title>{ABOUT_TITLE}</title><meta name="description" content={ABOUT_DESCRIPTION}/><link rel="canonical" href={base+'/about-us/'}/><meta property="og:title" content={ABOUT_TITLE}/><meta property="og:description" content={ABOUT_DESCRIPTION}/><meta property="og:url" content={base+'/about-us/'}/><meta property="og:type" content="website"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <section className="about-hero"><div className="about-wrap about-hero-grid"><div><span className="about-eyebrow">About Virtual Assistant Medical</span><h1>Behind every<br/>better day of care,<br/><span>there’s better support.</span></h1><p>Virtual Assistant Medical connects healthcare teams with remote support for the everyday work behind patient care. We help keep schedules, communication, and administration moving so your practice has more room to focus on people.</p><Link className="about-button" to="/contact-us/">Let’s Talk About Your Practice</Link></div><div className="about-hero-image"><img src="/images/about-vam-team.webp" alt="Healthcare support professionals collaborating at a laptop" width="1536" height="1024" fetchPriority="high"/><div className="about-image-caption"><strong>People behind the process</strong><span>Thoughtful support. Connected teams.</span></div></div></div></section>
 <section className="about-section about-who" id="who-we-are"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">Who we are</span><h2>A remote partner.<br/><span>Part of your daily rhythm.</span></h2></div><div className="about-who-grid"><div className="about-who-visual"><div className="about-who-photo"><img src="/images/about-connected-support.webp" alt="Healthcare practice administrator speaking with a remote medical assistant over a laptop video call" width="1536" height="1024" loading="lazy"/></div><div className="about-who-caption"><span className="about-icon"><AboutIcon kind={3}/></span><div><strong>Connected to your practice</strong><span>Support that works alongside your team</span></div></div></div><div className="about-who-copy"><p>Running a healthcare practice means balancing patient needs with a constant flow of calls, records, and administrative decisions. Virtual Assistant Medical—VAM—helps your team manage that everyday workload through focused remote assistance.</p><p>Our medical virtual assistants support scheduling, patient coordination, documentation, and office administration. Responsibilities are shaped around your practice’s priorities, with clear procedures and communication between your team and ours.</p><p>We believe useful support starts with understanding how your practice works. That means listening to the challenges your staff face, identifying tasks that can be handled remotely, and setting expectations before work begins.</p><ul className="about-who-focus" aria-label="Areas of support"><li><AboutIcon kind={4}/>Scheduling</li><li><AboutIcon kind={3}/>Patient coordination</li><li><AboutIcon kind={5}/>Documentation</li></ul></div></div></div></section>
 <section className="about-section about-purpose"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">Our purpose</span><h2>Less administrative pressure.<br/>More space for patient care.</h2></div><div className="about-purpose-grid"><article><span className="about-icon"><AboutIcon kind={0}/></span><h3>Our Mission</h3><p>To make the day-to-day work of healthcare practices easier through thoughtful, dependable remote support. We aim to reduce administrative friction, strengthen patient communication, and help healthcare teams use their time where it matters most.</p></article><article><span className="about-icon"><AboutIcon kind={1}/></span><h3>Our Vision</h3><p>A future where healthcare teams can access the right support for their workload, and remote colleagues feel like a connected part of the practice. We envision smoother operations, clearer communication, and more time for meaningful patient interactions.</p></article></div></div></section>
 <section className="about-section"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">What guides us</span><h2>Small details. Meaningful differences.</h2><p>The way a message is captured, a question is answered, or a follow-up is handled can change a patient’s experience. These values guide our approach.</p></div><div className="about-values">{values.map((v,i)=><article className={'about-value about-tone-'+i} key={v.title}><span className="about-icon"><AboutIcon kind={v.kind}/></span><h3>{v.title}</h3><p>{v.text}</p></article>)}</div></div></section>
 <section className="about-section about-services"><div className="about-wrap"><div className="about-editorial about-service-intro"><div><span className="about-eyebrow">How we help</span><h2>Support for the work<br/><span>that keeps care moving.</span></h2></div><p>Whether you run a solo practice, a growing clinic, or a multi-provider office, VAM helps you plan remote support around the administrative needs of your team.</p></div><div className="about-service-grid">{services.map(s=><article key={s.title}><span className="about-icon"><AboutIcon kind={s.kind}/></span><h3>{s.title}</h3><p>{s.text}</p><Link to={s.to}>Explore Support</Link></article>)}</div></div></section>
 <section className="about-section about-why"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">Why choose Virtual Assistant Medical</span><h2>Your practice comes first.<br/><span>Your support should reflect that.</span></h2></div><div className="about-reasons">{reasons.map(([title,text],i)=><article key={title}><span className="about-icon"><AboutIcon kind={i}/></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
 <section className="about-section about-partnership"><div className="about-wrap about-editorial"><div><span className="about-eyebrow">Working together</span><h2>A clear start.<br/>An evolving partnership.</h2><p>Good remote support is built around people, processes, and regular communication. Here’s how we bring those pieces together.</p></div><ol>{[['Understand your practice','Discuss your workload, coverage needs, systems, and the tasks you want to delegate. Define what successful support would look like for your team.'],['Set up the right support','Agree on responsibilities, approved access, communication channels, and escalation rules. Align support with your workflow before getting started.'],['Review and refine','Share feedback, review outstanding tasks, and revisit priorities as your practice changes. Keep improving the way your team and VAM work together.']].map(([title,text],i)=><li key={title}><span className="about-step-number">{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section className="about-section about-success"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">Build your next success story</span><h2>A clear plan.<br/><span>Support with room to grow.</span></h2><p>Start with the work your practice needs most, then shape a role around your team.</p></div><div className="about-number-grid">{[[18,'Support services','From patient calls to office coordination.'],[6,'Featured assistant roles','Focused responsibilities for different workflows.'],[3,'Partnership steps','Understand, set up, review and refine.']].map(([n,label,text])=><article key={label}><strong><AnimatedNumber value={Number(n)}/></strong><h3>{label}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="about-section about-reviews"><div className="about-wrap"><div className="about-section-heading"><span className="about-eyebrow">Practice reviews</span><h2>Healthcare professionals.<br/><span>In their own words.</span></h2></div><ReviewSlider reviews={TESTIMONIALS}/></div></section>
 <section className="about-section about-cta"><div className="about-wrap"><span className="about-eyebrow">Let’s build your support plan</span><h2>Tell us what’s taking<br/>time away from your team.</h2><p>Start with a conversation about your practice. We’ll discuss the work you need help with, the systems you use, and how Virtual Assistant Medical can fit into your day.</p><div className="about-cta-actions"><Link className="about-button" to="/contact-us/">Book a Consultation</Link><Link className="about-secondary" to="/services">View Our Services</Link></div></div></section>
 <RequestCallForm/>
 </div>
}
