import { useEffect, useState, type FormEvent } from 'react'
import './ContactPage.css'
export const CONTACT_TITLE='Contact Us | Virtual Assistant Medical'
export const CONTACT_DESCRIPTION='Contact Virtual Assistant Medical to discuss scheduling, patient communication, documentation, billing coordination, and remote support for your practice.'
const url='https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site/contact-us/'
const inbox='info@virtualassistantmedical.us'
export default function ContactPage(){
 const [draftRequested,setDraftRequested]=useState(false)
 useEffect(()=>{const tags=Array.from(document.querySelectorAll<HTMLMetaElement>('meta[name="robots"]'));const old=tags.map(t=>t.content);tags.forEach(t=>t.content='index, follow');return()=>tags.forEach((t,i)=>t.content=old[i])},[])
 function openDraft(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const lines=['VAM practice enquiry','',`Name: ${data.get('name')}`,`Email: ${data.get('email')}`,`Practice: ${data.get('practice')||'Not provided'}`,`Phone: ${data.get('phone')||'Not provided'}`,`Support needed: ${data.get('service')}`,'',String(data.get('message'))];window.location.href=`mailto:${inbox}?subject=${encodeURIComponent('VAM Enquiry: '+data.get('service'))}&body=${encodeURIComponent(lines.join('\n'))}`;setDraftRequested(true)}
 return <div className="vam-contact"><title>{CONTACT_TITLE}</title><meta name="description" content={CONTACT_DESCRIPTION}/><link rel="canonical" href={url}/><meta property="og:title" content={CONTACT_TITLE}/><meta property="og:description" content={CONTACT_DESCRIPTION}/><meta property="og:url" content={url}/><meta property="og:type" content="website"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'ContactPage',name:CONTACT_TITLE,url,description:CONTACT_DESCRIPTION})}}/>
 <section className="contact-hero"><div className="contact-wrap contact-hero-grid"><div className="contact-hero-copy"><span className="contact-eyebrow">Contact Virtual Assistant Medical</span><h1>Let’s talk about<br/><span>your practice.</span></h1><p>Tell us where your team needs support. We’ll help you explore a practical plan for your daily workload.</p></div><div className="contact-hero-visual"><img src="/images/contact-vam-assistant.webp" alt="Friendly medical virtual receptionist wearing a headset at a laptop" width="1536" height="1024" fetchPriority="high"/></div></div></section>
 <section className="contact-body"><div className="contact-wrap contact-grid"><div className="contact-details"><h2>A simpler next step.</h2><p>Ask about reception, scheduling, documentation, billing coordination, or other medical administrative support.</p><a className="contact-email" href={'mailto:'+inbox}><span className="contact-mail-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/></svg></span><span><strong>Email us</strong><span>{inbox}</span></span></a><div className="contact-next"><h3>What to share</h3><p>Your main tasks, preferred coverage hours, and the systems your practice uses.</p></div></div><form className="contact-form" onSubmit={openDraft} aria-labelledby="contact-form-title"><h2 id="contact-form-title">Tell us what you need</h2><div className="contact-form-grid"><label htmlFor="contact-name">Full name<input id="contact-name" name="name" autoComplete="name" required maxLength={120}/></label><label htmlFor="contact-email">Work email<input id="contact-email" name="email" type="email" autoComplete="email" required maxLength={254}/></label><label htmlFor="contact-practice">Practice name <span>(optional)</span><input id="contact-practice" name="practice" autoComplete="organization" maxLength={150}/></label><label htmlFor="contact-phone">Phone <span>(optional)</span><input id="contact-phone" name="phone" type="tel" autoComplete="tel" maxLength={40}/></label></div><label htmlFor="contact-service">Support needed<select id="contact-service" name="service" required defaultValue=""><option value="" disabled>Select a service</option>{['Virtual Medical Receptionist','Virtual Medical Scribe','Medical Administrative Support','Medical Billing Support','Medical Coding Support','Remote Patient Monitoring Support','Help choosing the right support'].map(s=><option key={s}>{s}</option>)}</select></label><label htmlFor="contact-message">How can we help?<textarea id="contact-message" name="message" rows={4} required maxLength={2000}/></label><p className="contact-form-note">Please leave out patient details. This form opens an email draft for you to review and send.</p><button type="submit">Open Email Draft</button>{draftRequested&&<p className="contact-draft-status" role="status">Send the draft from your email app to complete your enquiry. If it didn’t open, email us directly at <a href={'mailto:'+inbox}>{inbox}</a>.</p>}</form></div></section>
 </div>
}
