import { Link } from 'react-router'
import ServiceFAQs from '../components/ServiceFAQs'
import { FEATURED_ROLES } from '../data/roles'
import './HiringYourVAPage.css'
export const HIRING_TITLE='Hiring Your Medical Virtual Assistant | VAM'
export const HIRING_DESCRIPTION='Plan hiring your VA with VAM. Explore role selection, candidate fit, workflow setup and onboarding for your medical practice in six clear steps.'
const stages=[['Start with your practice','Share the tasks taking up your team’s time, your specialty, software and preferred coverage hours. Together, we identify a focused starting point.','A clear picture of your workload'],['Define the role','Agree which tasks can be delegated, which need approval and who handles exceptions. Confirm any required credentials, languages or specialty experience.','Responsibilities and requirements'],['Review the proposed fit','Discuss the proposed assistant’s relevant experience, communication style and familiarity with your workflows. Ask practical questions before agreeing to an assignment.','A role matched to your requirements'],['Confirm the working plan','Review scheduled hours, responsibilities, pricing and terms in your proposal. Agree how task updates and feedback will reach your team.','Shared expectations before work begins'],['Prepare approved access','Arrange the BAA, role-based system access, approved communication channels and practice instructions. Confirm the escalation contact and review responsibilities.','A ready-to-use onboarding plan'],['Start, review and refine','Begin with the agreed tasks. Review completed work and unresolved items during early check-ins, then refine priorities as the workflow settles.','A consistent feedback routine']]
const faqs=[{q:'How do I choose the right VA role?',a:'Start with the work that repeats each week and the tasks your on-site team wants to delegate. Share those priorities with VAM so we can discuss a focused role, the experience needed and the appropriate review process.'},{q:'Can we discuss the proposed assistant before getting started?',a:'Candidate fit and your questions should be reviewed before assignment. Discuss relevant experience, communication, schedule and workflow requirements during the consultation so expectations are clear.'},{q:'How long does hiring and onboarding take?',a:'Timing depends on role availability, required experience, your software and how quickly onboarding requirements can be completed. We discuss a realistic start date after reviewing your needs.'},{q:'What should we prepare for the first conversation?',a:'Bring a short task list, preferred hours and time zone, the systems you use, any required credentials and the person who will supervise or review the work. Patient information is not needed for the initial conversation.'},{q:'What does support cost?',a:'VAM virtual assistant support starts at $9.50 per hour. The role, coverage hours and full terms are confirmed in your proposal. Visit Pricing for an illustrative comparison with in-house support.'},{q:'Who manages system access and patient information?',a:'Your practice approves system permissions, communication channels and security procedures. Agree the Business Associate Agreement and role-based access before patient information is shared. Clinical decisions and final approvals remain with the responsible team.'}]
function HiringIcon({i}:{i:number}){const paths=['M4 4h16v12H9l-5 4z M8 8h8 M8 12h5','M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5','M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6','M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16','M8 11V7a4 4 0 0 1 8 0v4 M5 11h14v10H5z','M4 20V10 M10 20V4 M16 20v-7 M2 20h20'];return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[i%6]}/></svg>}
export default function HiringYourVAPage(){return <main className="vam-hiring"><title>{HIRING_TITLE}</title><meta name="description" content={HIRING_DESCRIPTION}/><link rel="canonical" href="https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site/hiring-your-va/"/>
<section className="hiring-hero"><div className="hiring-wrap hiring-hero-grid"><div><nav aria-label="Breadcrumb"><Link to="/">Home</Link><span> / Hiring Your VA</span></nav><span className="hiring-eyebrow">Hiring Your VA with VAM</span><h1>The right support.<br/><em>A clear way to start.</em></h1><p>Hiring a medical virtual assistant starts with understanding your practice. From the first conversation to your first week together, build a role with clear tasks, practical expectations and thoughtful onboarding.</p><div className="hiring-actions"><Link className="hiring-button" to="/contact-us/">Discuss Your VA Needs</Link><a className="hiring-secondary" href="#hiring-process">Explore the Six Steps</a></div></div><div className="hiring-hero-image"><img src="/images/hiring-va-consultation.webp" alt="Professionals interviewing a candidate on a laptop video call" width="2000" height="1335" fetchPriority="high"/><div><span>From conversation to collaboration</span><strong>Your practice guides the plan.</strong></div></div></div></section>
<section className="hiring-section" id="hiring-process"><div className="hiring-wrap"><div className="hiring-heading"><span className="hiring-eyebrow">Your hiring journey</span><h2>Six steps. One shared plan.</h2><p>Know what to discuss, what to prepare and what happens next.</p></div><ol className="hiring-stages">{stages.map(([title,text,outcome],i)=><li key={title}><div className="hiring-stage-top"><span className="hiring-number">0{i+1}</span><span className={'hiring-icon hiring-tone-'+i}><HiringIcon i={i}/></span></div><h3>{title}</h3><p>{text}</p><div className="hiring-outcome"><span>What you leave with</span><strong>{outcome}</strong></div></li>)}</ol></div></section>
<section className="hiring-section hiring-ready"><div className="hiring-wrap hiring-split"><div><span className="hiring-eyebrow">Before we talk</span><h2>A little preparation.<br/>A more useful conversation.</h2><p>You don’t need a finished job description. Bring the everyday tasks that feel difficult to keep up with, and we’ll help you discuss a practical scope.</p><Link className="hiring-button" to="/contact-us/">Start the Conversation</Link></div><div className="hiring-checklist"><h3>Your consultation checklist</h3><ul>{['Your specialty and practice size','Tasks you want to delegate','EHR, scheduling and billing systems','Preferred coverage hours and time zone','Required experience, credentials or languages','Who will review work and handle exceptions'].map(t=><li key={t}>{t}</li>)}</ul><p>Please leave patient details out of your initial enquiry.</p></div></div></section>
<section className="hiring-section"><div className="hiring-wrap"><div className="hiring-heading"><span className="hiring-eyebrow">Choose your starting point</span><h2>A role for the work you need handled.</h2><p>Explore the responsibilities, then discuss which role fits your priorities.</p></div><div className="hiring-role-grid">{FEATURED_ROLES.map((r,i)=><Link to={r.slug==='virtual-medical-scribe'?'/virtual-medical-scribe/':r.slug==='virtual-medical-receptionist'?'/virtual-medical-receptionist/':'/services/'+r.slug+'/'} key={r.slug}><span className={'hiring-icon hiring-tone-'+i}><HiringIcon i={i}/></span><strong>{r.title}</strong><span>{r.tagline}</span></Link>)}</div></div></section>
<section className="hiring-section hiring-first-week"><div className="hiring-wrap hiring-split"><div><span className="hiring-eyebrow">Beyond the first day</span><h2>Make the first week<br/>a useful foundation.</h2><p>Begin with agreed priorities and a manageable task queue. Clear feedback helps your assistant understand your preferences and helps your team see where the process needs adjustment.</p></div><div className="hiring-week-points">{[['Keep a clear handoff','Record the task, the expected outcome and who handles questions.'],['Review the work together','Check completed tasks and unresolved items at agreed intervals.'],['Refine the priorities','Update instructions as you learn what works best for your team.']].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="hiring-section hiring-cta hiring-cta-portrait"><div className="hiring-wrap"><div className="hiring-cta-copy"><span className="hiring-eyebrow">Your next step</span><h2>Let’s define your<br/>first VA role.</h2><p>Tell us what is taking time from your team and where you would like support.</p><Link className="hiring-button" to="/contact-us/">Book a Free Consultation</Link></div><div className="hiring-cta-visual"><img src="/images/hiring-vam-female.webp" alt="Female medical virtual assistant wearing a headset and scrubs with VAM branding" width="1448" height="1086" loading="lazy"/></div></div></section>
<ServiceFAQs id="hiring-faqs" title="Hiring Your VA FAQs" items={faqs} schema/>
</main>}
