import { Link } from 'react-router'
import ServiceFAQs from '../components/ServiceFAQs'
import ReviewSlider from '../components/ReviewSlider'
import { TESTIMONIALS } from '../data/testimonials'
import billingPortrait from '../assets/role-billing-scrubs.png'
import './MedicalBillingPage.css'
export const BILLING_TITLE='Medical Billing Virtual Assistant Services | VAM'
export const BILLING_DESCRIPTION='Keep billing tasks organized with VAM medical billing virtual assistants. Get support for claims, payment posting, denials and accounts receivable from $9.50/hour.'
const base='https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site/services/medical-billing-assistant/'
const tasks=[['Claims preparation & tracking','Check administrative details, prepare claims within your approved workflow, and track submission responses. Flag missing information before it becomes another unresolved task.'],['Insurance verification','Confirm eligibility information, benefits and payer details through your approved portals. Bring coverage questions to the right member of your team.'],['Payment posting support','Organize ERA and EOB information, post payments and approved adjustments, and flag mismatches for your billing lead to review.'],['Denial & rejection follow-up','Record payer reasons, gather requested documentation, and support corrections or resubmissions under your team’s direction.'],['Accounts receivable follow-up','Work your assigned aging queues, check outstanding claim status, and record the next action so follow-ups stay visible.'],['Patient billing communication','Respond to routine balance questions using your scripts, explain approved payment information, and route disputes or exceptions to your practice.']]
const faqs=[{q:'What does a medical billing virtual assistant do?',a:'A medical billing virtual assistant supports the administrative work behind your revenue cycle. VAM can help with claim tracking, insurance checks, payment posting, denial follow-up, patient billing messages and accounts receivable. Your agreed scope determines which tasks are included.'},{q:'Can VAM work in our existing billing software?',a:'We review your billing platform, clearinghouse and payer portals during the consultation. Access permissions, training needs and task responsibilities are agreed before onboarding. Your practice keeps its existing systems.'},{q:'Can an assistant help with denied claims and aging accounts?',a:'Yes. Support can include checking payer responses, documenting denial reasons, gathering missing information, following assigned aging queues and preparing items for review. Appeals, adjustments and write-offs follow your approval procedures.'},{q:'How do you handle patient information?',a:'Before access begins, agree the Business Associate Agreement, role-based permissions, approved communication channels and your practice’s security procedures. Your assistant should use only the access needed for the assigned work.'},{q:'Is medical coding included in billing support?',a:'Coding and billing are related but distinct responsibilities. Discuss any coding needs separately so credentials, specialty experience and review requirements can be confirmed. Providers remain responsible for clinical documentation and final approvals.'},{q:'How much does a medical billing assistant cost?',a:'VAM virtual assistant support starts at $9.50 per hour. Confirm the billing role, scheduled hours, responsibilities and full terms in your proposal. A 20-hour week at this rate is $190 before any separately agreed services.'},{q:'Can you support practices in different US states?',a:'Remote support can be planned around US practice workflows. Tell us your state, specialty, payer mix, time zone and coverage hours so we can review the requirements and confirm a suitable arrangement.'},{q:'How do we get started?',a:'Book a consultation and share your software, biggest billing bottlenecks, weekly workload and preferred schedule. We agree the scope, review assistant fit, arrange approved access and set up a reporting routine before work begins.'}]
function BillingIcon({i}:{i:number}){const paths=['M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h4','M3 5h18v14H3z M3 10h18 M7 15h4 M16 14v3','M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 16l3 3 5-5','M4 4h16v12H9l-5 4z M8 8h8 M8 12h4','M4 20V10 M10 20V4 M16 20v-7 M2 20h20','M4 5h16v14H4z M4 6l8 7 8-7'];return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[i%6]}/></svg>}
export default function MedicalBillingPage(){return <main className="vam-billing"><title>{BILLING_TITLE}</title><meta name="description" content={BILLING_DESCRIPTION}/><link rel="canonical" href={base}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Service',name:'Medical Billing Virtual Assistant',url:base,provider:{'@type':'Organization',name:'Virtual Assistant Medical'}})}}/>
<section className="vb-hero"><div className="vb-wrap vb-hero-grid"><div><nav className="vb-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/services">Services</Link><span>/ Billing</span></nav><span className="vb-eyebrow">Virtual Assistant Medical</span><h1>Medical billing support.<br/><em>More clarity. Less chasing.</em></h1><p>Your billing team needs time to work the queue—not another queue to manage. A VAM medical billing virtual assistant helps organize claims, payer follow-ups and payment information inside your existing workflow.</p><div className="vb-actions"><Link className="vb-button" to="/contact-us/">Find Your Billing Assistant</Link><a className="vb-button vb-outline" href="#billing-services">Explore Billing Support</a></div><ul className="vb-hero-points"><li>Practice-approved processes</li><li>Clear task updates</li><li>From $9.50/hour</li></ul></div><div className="vb-hero-art"><img src={billingPortrait} alt="Medical billing assistant in blue scrubs with a headset" width="1024" height="1536" fetchPriority="high"/><div className="vb-hero-note"><span><BillingIcon i={4}/></span><div><strong>Keep the next action clear</strong><p>Claims · Payments · Follow-ups</p></div></div></div></div></section>
<section className="vb-section"><div className="vb-wrap vb-split"><div className="vb-photo"><img src="/images/billing-team-support.webp" alt="Medical billing professional wearing a headset and reviewing paperwork at a desktop workstation" width="1600" height="1100" loading="lazy"/></div><div><span className="vb-eyebrow">An extension of your billing team</span><h2>Make room for the work that needs your attention.</h2><p>Billing work moves through many hands. Missing payer details, unresolved responses and inconsistent notes make it harder to see what comes next.</p><p>VAM supports the daily administrative steps around your revenue cycle. Your assistant follows your work queues, escalation rules and reporting preferences, while your billing lead keeps control of decisions and exceptions.</p><Link className="vb-text-link" to="/contact-us/">Discuss Your Billing Workflow</Link></div></div></section>
<section className="vb-section vb-light" id="billing-services"><div className="vb-wrap"><div className="vb-heading"><span className="vb-eyebrow">From eligibility to follow-up</span><h2>Billing tasks that keep<br/>your practice moving.</h2><p>Choose a focused assignment or combine several responsibilities into one agreed support role.</p></div><div className="vb-task-grid">{tasks.map(([title,text],i)=><article key={title} className={'vb-task vb-tone-'+i}><span className="vb-icon"><BillingIcon i={i}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="vb-section"><div className="vb-wrap"><div className="vb-heading"><span className="vb-eyebrow">A practical start</span><h2>Your process, before our first task.</h2></div><ol className="vb-steps">{[['Map the workload','Review your specialty, payer mix, software, aging queues and weekly coverage needs.'],['Agree the right role','Confirm responsibilities, required experience, access permissions and approval limits.'],['Set up your workflow','Arrange the BAA, approved system access, work instructions and escalation contacts.'],['Start, review, refine','Begin the assigned queues and review task updates, unresolved items and changing priorities.']].map(([title,text],i)=><li key={title}><span>{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
<section className="vb-section vb-navy"><div className="vb-wrap vb-split"><div><span className="vb-eyebrow">Visibility without micromanaging</span><h2>Know what was worked.<br/>Know what needs you.</h2><p>Agree on the updates that matter to your practice: claims followed up, payer responses, payment discrepancies and items waiting for approval.</p><p>Patient data stays within your approved access and communication procedures. Clinical documentation, coding decisions, appeals and financial exceptions remain subject to the right team’s review.</p></div><div className="vb-report"><span className="vb-eyebrow">A useful reporting routine</span><h3>A clear handoff at the end of the day</h3><ul><li>Tasks completed in your assigned queues</li><li>Outstanding items and their next actions</li><li>Payer responses and documentation requests</li><li>Exceptions needing your billing lead</li></ul><span className="vb-report-note">Reporting format and frequency agreed during onboarding.</span></div></div></section>
<section className="vb-section vb-light"><div className="vb-wrap"><div className="vb-heading"><span className="vb-eyebrow">Keep your existing setup</span><h2>Billing support inside your tools.</h2><p>We review platform experience and training needs before assignment. You retain control of your software, accounts and permissions.</p></div><div className="vb-platforms">{['EHR & practice management','Clearinghouse work queues','Payer portals','ERA & EOB workflows','Patient billing messages','Aging reports'].map((s,i)=><div key={s}><BillingIcon i={i}/><span>{s}</span></div>)}</div></div></section>
<section className="vb-section vb-reviews" aria-labelledby="billing-review-heading"><div className="vb-wrap"><div className="vb-heading"><span className="vb-eyebrow">Practice reviews</span><h2 id="billing-review-heading">What healthcare professionals say.</h2></div><ReviewSlider reviews={TESTIMONIALS}/></div></section>
<section className="vb-section" id="billing-us"><div className="vb-wrap vb-map-grid"><div><span className="vb-eyebrow">Remote support for US practices</span><h2>Your practice location.<br/>Your working hours.</h2><p>Build medical billing support around your state, specialty, payer mix and time zone. Share your requirements so we can confirm the right fit and coverage.</p><p>From independent clinics to multi-provider practices, the starting point is the same: your processes, your approved access and your team’s priorities.</p><Link className="vb-button" to="/contact-us/">Discuss Support in Your State</Link></div><figure className="vb-map"><iframe title="Google Map of the United States service area" src="https://maps.google.com/maps?q=United%20States&z=3&output=embed" width="960" height="420" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="vb-map-link" href="https://www.google.com/maps/place/United+States/" target="_blank" rel="noopener noreferrer">Open in Google Maps</a><figcaption>United States service market · remote support, not office locations</figcaption></figure></div></section>
<section className="vb-section vb-cta"><div className="vb-wrap"><div><span className="vb-eyebrow">Put your billing backlog in focus</span><h2>Start with your biggest bottleneck.</h2><p>Tell us what is waiting, which systems you use and how many hours of support you need. We’ll help you define a practical billing role.</p></div><div><Link className="vb-button" to="/contact-us/">Book a Free Consultation</Link><Link className="vb-text-link" to="/pricing/">Compare VAM Pricing</Link></div></div></section>
<ServiceFAQs id="billing-faqs" title="Medical Billing Assistant FAQs" items={faqs} schema/>
</main>}
