import { useEffect } from 'react'
import { Link } from 'react-router'
import { SERVICES } from '../data/services'
import { FEATURED_ROLES } from '../data/roles'
import './ServicesPage.css'
export const SERVICES_TITLE='Medical Virtual Assistant Services | VAM'
export const SERVICES_DESCRIPTION='Explore VAM medical virtual assistant services for reception, scribing, billing, coding, patient coordination, and everyday practice administration.'
const base='https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site'
const groups=[{id:'front-desk',title:'Front desk & patient communication',intro:'Make every routine interaction easier to manage, from the first call to the next appointment.',slugs:['phone-answering','appointment-scheduling','patient-communication','patient-intake-support','healthcare-customer-service']},{id:'records',title:'Records, documentation & systems',intro:'Keep administrative information organized and accessible within your approved tools.',slugs:['medical-records-support','ehr-administrative-support','documentation-data-entry','inbox-email-management']},{id:'billing',title:'Billing & insurance administration',intro:'Keep payer requests, billing information, and follow-ups moving alongside your revenue cycle team.',slugs:['insurance-verification','prior-authorization-support','medical-billing-support','claims-follow-up']},{id:'coordination',title:'Practice coordination & operations',intro:'Connect the everyday tasks that help your office run smoothly, with clear ownership and handoffs.',slugs:['medical-virtual-assistant','referral-coordination','prescription-refill-coordination','provider-calendar-management','back-office-administrative-support']}]
const descriptions:Record<string,string>={
 'medical-virtual-assistant':'Bring several administrative responsibilities into one coordinated support role. VAM can help with scheduling, patient messages, records preparation, and task tracking, with priorities agreed around your practice’s daily needs.',
 'appointment-scheduling':'Keep bookings, rescheduling, cancellations, and appointment confirmations organized. Your assistant follows your calendar rules and helps patients understand the next steps, while scheduling exceptions reach the right person on your team.',
 'patient-communication':'Support routine patient calls, approved reminders, and follow-up messages with clear, considerate communication. Track outstanding requests and pass clinical questions to your healthcare team using the routing procedures you define.',
 'insurance-verification':'Collect and check eligibility and benefit information before visits using your approved payer tools. Record coverage details and flag missing or unclear information for review by your billing or front-desk team.',
 'prior-authorization-support':'Coordinate the administrative side of authorization requests. Organize documents, track payer responses, and follow up on outstanding items while your clinicians provide the medical information and decisions required.',
 'medical-billing-support':'Support charge information preparation, payment record organization, and billing work queues. Your assistant follows your billing platform and review process, keeping discrepancies visible to the person responsible for resolving them.',
 'claims-follow-up':'Check claim status, record payer responses, and keep follow-up actions organized. VAM helps your billing team see what is pending, which information is missing, and which items need further review.',
 'patient-intake-support':'Help patients complete registration details and gather required forms before their visit. Organize administrative information and identify incomplete items so your team can prepare for the appointment with fewer last-minute requests.',
 'referral-coordination':'Track referral documents, receiving-office requirements, and appointment follow-ups. Keep updates visible to your practice and route outstanding questions to the appropriate provider or staff member.',
 'medical-records-support':'Organize records requests, document uploads, and administrative file preparation. Follow your authorization and release procedures, with sensitive requests and exceptions escalated to your designated team member.',
 'prescription-refill-coordination':'Capture refill requests and route them to licensed staff. Track administrative details and approved follow-up messages; prescribing, approval, and medication advice remain with your clinical team.',
 'inbox-email-management':'Sort shared inboxes, route messages, and track outstanding replies according to your priorities. Routine administrative responses follow approved templates, while sensitive or clinical questions are handed to the right person.',
 'phone-answering':'Give patients a professional point of contact during your agreed coverage hours. Capture messages, handle routine questions, and route calls using your practice’s scripts and escalation rules.',
 'ehr-administrative-support':'Maintain patient demographics, scheduling information, and administrative records within your EHR. Work is planned around approved permissions, documentation standards, and the updates your practice needs.',
 'documentation-data-entry':'Help with forms, administrative data entry, and record preparation. Your assistant follows agreed formats, flags missing information, and keeps completed work ready for review by your practice team.',
 'provider-calendar-management':'Coordinate provider calendars, administrative meetings, and availability updates. Follow individual scheduling preferences, identify conflicts, and route changes that need approval before they affect the day’s plans.',
 'healthcare-customer-service':'Support patient enquiries about appointments, forms, and routine practice information with a helpful, consistent tone. Keep requests documented and send complaints or questions outside the agreed scope to your team.',
 'back-office-administrative-support':'Keep internal task lists, reports, document organization, and routine coordination moving. VAM helps practice managers delegate agreed administrative work while retaining visibility over priorities and progress.'
}
const roleCopy:Record<string,string>={
 'virtual-medical-receptionist':'Create a welcoming first point of contact for your patients. Support calls, appointments, reminders, and intake while your on-site team focuses on the people in front of them.',
 'virtual-medical-scribe':'Make room for patient conversations with documentation support. Prepare encounter notes and organize EHR information within your approved workflow, ready for the provider’s review and sign-off.',
 'medical-admin-assistant':'Connect the details behind your practice’s day. Coordinate inboxes, records requests, referrals, and outstanding tasks so your team has a clearer view of what needs attention.',
 'virtual-medical-coder':'Support coding workflows through documentation review, coding queries, and correction tracking. Confirm the credentials, specialty experience, and review requirements needed for your assignment before work begins.',
 'remote-patient-monitoring-support':'Help patients get started with your monitoring program through enrollment coordination, device setup instructions, and approved reminders. Route concerns to your clinical team for assessment and care decisions.',
 'medical-billing-assistant':'Keep billing tasks moving with claim tracking, payment information organization, and payer follow-ups. Your assistant works alongside your billing lead within your platform and agreed review process.'
}
function ServiceIcon({kind=0}:{kind?:number}){const paths=['M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 15l3 3 5-5','M4 4h16v12H9l-5 4z M8 8h8 M8 12h5','M5 3h14v18H5z M9 7h6 M9 11h6 M9 15h4','M3 5h18v14H3z M3 10h18 M7 15h3 M16 14v3 M14.5 15.5h3','M4 3h16v18H4z M8 7h8 M8 11h8 M8 15h5 M8 18h3','M8 10a3 3 0 1 0 0-6a3 3 0 1 0 0 6 M2 21v-3a6 6 0 0 1 12 0v3 M17 4a3 3 0 0 1 0 6 M18 14c3 0 4 2 4 4v3'];return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind%6]}/></svg>}
function servicePath(slug:string){return ['virtual-medical-scribe','virtual-medical-receptionist'].includes(slug)?'/'+slug+'/':'/services/'+slug}
export default function ServicesPage(){
 useEffect(()=>{const tags=Array.from(document.querySelectorAll<HTMLMetaElement>('meta[name="robots"]'));const old=tags.map(t=>t.content);tags.forEach(t=>t.content='index, follow');return()=>tags.forEach((t,i)=>t.content=old[i])},[])
 const schema={'@context':'https://schema.org','@type':'CollectionPage',name:SERVICES_TITLE,url:base+'/services/',description:SERVICES_DESCRIPTION,mainEntity:{'@type':'ItemList',itemListElement:FEATURED_ROLES.map((r,i)=>({'@type':'ListItem',position:i+1,name:r.title,url:base+servicePath(r.slug)}))}}
 return <div className="vam-services"><title>{SERVICES_TITLE}</title><meta name="description" content={SERVICES_DESCRIPTION}/><link rel="canonical" href={base+'/services/'}/><meta property="og:title" content={SERVICES_TITLE}/><meta property="og:description" content={SERVICES_DESCRIPTION}/><meta property="og:url" content={base+'/services/'}/><meta property="og:type" content="website"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <section className="vs-hero"><div className="vs-wrap vs-hero-grid"><div><span className="vs-eyebrow">Virtual Assistant Medical services</span><h1>The right support.<br/><span>A better practice day.</span></h1><p>From the first patient call to the final administrative follow-up, VAM helps your team keep everyday work moving. Explore medical virtual assistant services built around your people, priorities, and existing systems.</p><div className="vs-actions"><a className="vs-button" href="#services-grid">Explore Services</a><Link className="vs-hero-link" to="/contact-us/">Discuss Your Needs</Link></div></div><div className="vs-hero-image"><img src="/images/services-vam-support.webp" alt="Medical virtual assistant and physician collaborating at a laptop" width="1536" height="1024" fetchPriority="high"/><div className="vs-hero-caption"><strong>Support shaped around your practice</strong><span>Patient communication · Documentation · Administration</span></div></div></div></section>
 <section className="vs-section" id="services-grid"><div className="vs-wrap"><div className="vs-heading"><span className="vs-eyebrow">Choose your support role</span><h2>Six ways to strengthen<br/>your healthcare team.</h2><p>Start with the role that fits your workload. We’ll discuss the tasks, coverage, experience, and access your practice needs.</p></div><div className="vs-roles">{FEATURED_ROLES.map((r,i)=><article className={'vs-role vs-tone-'+i} key={r.slug}><span className="vs-icon"><ServiceIcon kind={i}/></span><h3>{r.title}</h3><p>{roleCopy[r.slug]}</p><Link to={servicePath(r.slug)}>View Service Details</Link></article>)}</div></div></section>
 <section className="vs-directory"><div className="vs-wrap"><div className="vs-heading"><span className="vs-eyebrow">Everyday practice support</span><h2>Explore the work<br/><span>you can delegate.</span></h2><p>Browse all 18 administrative services. Combine related tasks into a practical support plan for your office.</p></div><nav className="vs-jump" aria-label="Browse service categories">{groups.map(g=><a key={g.id} href={'#vs-'+g.id}>{g.title}</a>)}</nav></div></section>
 {groups.map((g,groupIndex)=><section key={g.id} className={'vs-section vs-group vs-group-'+groupIndex} id={'vs-'+g.id} aria-labelledby={'vs-title-'+g.id}><div className="vs-wrap"><div className="vs-group-heading"><span className="vs-icon"><ServiceIcon kind={groupIndex}/></span><div><h2 id={'vs-title-'+g.id}>{g.title}</h2><p>{g.intro}</p></div></div><div className="vs-task-grid">{g.slugs.map(slug=>{const service=SERVICES.find(s=>s.slug===slug)!;return <article key={slug}><h3>{service.shortTitle}</h3><p>{descriptions[slug]}</p><Link to={'/services/'+slug}>Explore This Service</Link></article>})}</div></div></section>)}
 <section className="vs-section vs-plan"><div className="vs-wrap vs-plan-grid"><div><span className="vs-eyebrow">Your workflow leads the way</span><h2>One practice.<br/><span>Your own support plan.</span></h2><p>Start with your most time-consuming tasks. Together, we can define a role that fits your systems, coverage requirements, and priorities.</p><Link className="vs-button" to="/contact-us/">Plan Your Support</Link></div><ol>{[['Define the work','Identify the responsibilities you want to delegate and which decisions stay with your team.'],['Align the workflow','Agree on approved access, communication channels, task ownership, and escalation rules.'],['Review and adapt','Use feedback and regular updates to refine priorities as your practice’s needs change.']].map(([title,text],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section className="vs-section vs-cta"><div className="vs-wrap"><h2>Not sure which service fits?</h2><p>Tell us what’s slowing down your practice. We’ll help you identify a useful starting point.</p><Link className="vs-button" to="/contact-us/">Talk to VAM</Link></div></section>
 </div>
}
