import { Fragment, useEffect, useRef, useState } from 'react'
import ServiceFAQs from '../components/ServiceFAQs'
import { RECEPTION_SECTIONS as sections, RECEPTION_FAQS as faqs } from '../data/receptionist'
import portrait from '../assets/role-receptionist-scrubs.png'
import assistant from '../assets/reception-intro-new.png'
import doctor from '../assets/scribe-doctor-visit.png'
import logo from '../assets/logo1.png'
import communicationAssistant from '../assets/practice-support-assistant.png'
import resultsDoctor from '../assets/scribe-doctor-review.png'
import './VirtualMedicalReceptionistPage.css'
export const RECEPTION_TITLE='Virtual Medical Receptionist Services | VAM'
export const RECEPTION_DESCRIPTION='VAM virtual medical receptionist services support patient calls, appointment scheduling, reminders and front-desk tasks. Contact our team for tailored support.'
const receptionistFAQs=[...faqs, ['Can a receptionist follow our existing scheduling procedures?', 'Yes. VAM receptionists work according to your appointment rules, call scripts, office hours, and message-routing preferences. Your team defines which requests they handle and which should be escalated.'], ['Can I adjust the amount of reception support my practice needs?', 'Discuss your call volume, coverage hours, and administrative priorities with VAM. Support can be planned around your current workflow and reviewed as your practice’s needs change.']]
const url='https://virtual-assistant-medical.ahmed-raza276082.chatgpt.site/virtual-medical-receptionist/'
const contact='mailto:info@virtualassistantmedical.us?subject=Virtual%20Medical%20Receptionist%20Enquiry'
const schema={'@context':'https://schema.org','@graph':[{'@type':'Service',name:'Virtual Medical Receptionist',serviceType:'Remote medical reception support',url,provider:{'@type':'Organization',name:'Virtual Assistant Medical'}},{'@type':'FAQPage',mainEntity:receptionistFAQs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:url.split('/virtual-')[0]+'/'},{'@type':'ListItem',position:2,name:'Virtual Medical Receptionist',item:url}]}]}
function Icon({kind=0}:{kind?:number}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind%4===0?<><rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-11 5 2 2 4-4"/></>:kind%4===1?<><path d="M5 4h4l2 5-3 2a16 16 0 0 0 5 5l2-3 5 2v4c0 2-3 2-5 1C8 18 3 12 3 6c0-1 1-2 2-2Z"/></>:kind%4===2?<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/></>:<><path d="M4 4h16v12H9l-5 4Z"/><path d="M8 8h8m-8 4h5"/></>}</svg>}
function Paragraphs({index}:{index:number}){return <>{sections[index].paragraphs.map((p,i)=><p key={i} dangerouslySetInnerHTML={{__html:p}}/>)}</>}
function ReceptionTaskIcon({index}:{index:number}){
 const paths=[
 'M5 3h4l2 5-3 2a16 16 0 0 0 6 6l2-3 5 2v4c0 2-3 2-5 1C8 17 3 11 3 5c0-1 1-2 2-2Z',
 'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 15h8 M14 13l2 2-2 2',
 'M6 9a6 6 0 0 1 12 0v6l2 3H4l2-3z M10 21h4 M12 6v4',
 'M4 4h16v12H9l-5 4z M8 9l3 3 5-5',
 'M3 5h18v14H3z M3 10h18 M7 15h3 M16 14v3 M14.5 15.5h3',
 'M9 3h6v4H9z M9 5H5v16h14V5h-4 M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0 M8 19c0-4 8-4 8 0',
 'M3 5h12v9H8l-5 3z M18 9h3v11h-8v-3 M7 9h4 M17 5l2-2 2 2 M19 3v4',
 'M9 3h6v4H9z M9 5H5v16h14V5h-4 M8 11l1 1 2-2 M13 11h3 M8 16l1 1 2-2 M13 16h3',
 'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 16l3 3 5-6',
 'M12 3l10 18H2z M12 9v5 M12 17v.5'
 ];
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[index]}/></svg>
}
function ReceptionOfficeSupport(){
 const section=sections[2];
 return <section id="reception-section-2" className="reception-office-support" aria-labelledby="reception-office-title"><div className="reception-wrap"><div className="reception-office-heading"><h2 id="reception-office-title">{section.title}</h2><div className="reception-office-rule" aria-hidden="true"/><p dangerouslySetInnerHTML={{__html:section.paragraphs[0]}}/><p className="reception-office-intro">{section.paragraphs[1]}</p></div><ul className="reception-office-tasks">{section.items.map((item,i)=><li key={item} className={`reception-office-task reception-task-tone-${i%5}`}><span className="reception-task-icon"><ReceptionTaskIcon index={i}/></span><h3>{item}</h3></li>)}</ul><p className="reception-office-footer">{section.paragraphs[2]}</p></div></section>
}
function ReceptionHighlights(){
 const highlights=[{title:'Privacy-conscious',text:'Patient information handled within your access requirements',icon:2},{title:'Practice-aligned',text:'Reception support shaped around your workflow',icon:0},{title:'Patient-focused',text:'Professional communication for every routine enquiry',icon:3},{title:'Flexible support',text:'Call handling and scheduling as your practice grows',icon:1}]
 return <section className="reception-highlights" aria-labelledby="reception-highlights-title"><div className="reception-wrap"><div className="reception-highlights-panel"><div className="reception-highlights-content"><h2 id="reception-highlights-title">The VAM Difference at Your Front Desk</h2><div className="reception-highlights-rule"/><ul className="reception-highlights-grid">{highlights.map(item=><li key={item.title}><span className="reception-icon"><Icon kind={item.icon}/></span><div><h3>{item.title}</h3><p>{item.text}</p></div></li>)}</ul></div><div className="reception-highlights-visual"><img src={resultsDoctor} alt="Physician in a white coat reviewing information at a laptop" width="1536" height="1024" loading="lazy"/><div className="reception-highlights-caption"><p>Virtual Assistant Medical helps your team stay responsive while you focus on care. From patient calls to appointment coordination, our receptionists follow your processes and keep everyday front-desk tasks moving.</p></div></div></div></div></section>
}
function ReceptionPracticeSupport(){
 const options=[
 {title:'Physician EHR Support',text:'Keep front-desk information organized in your existing EHR. VAM can help update patient demographics, appointment details, and administrative records using your approved access and procedures.',path:'M4 3h16v18H4z M8 7h8 M8 11h8 M8 15h4'},
 {title:'Billing Coordination',text:'Help patients reach the right billing contact, collect requested insurance information, and route payment enquiries. VAM keeps administrative follow-ups moving alongside your billing team.',path:'M5 3h14v18l-3-2-4 2-4-2-3 2z M8 8h8 M8 12h5'},
 {title:'Appointment Management',text:'Coordinate new bookings, reschedule visits, and manage cancellations according to your calendar rules. Reminders and follow-ups help patients stay informed about their next appointment.',path:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 15l3 3 5-5'},
 {title:'Patient Records Preparation',text:'Organize intake forms, check for missing administrative details, and prepare records for your team’s review. Clinical information and documentation remain subject to your practice’s verification.',path:'M3 6h7l2 3h9v12H3z M7 3h10v6 M8 14h8 M8 17h5'},
 {title:'General Administration',text:'Bring order to shared inboxes, task lists, and everyday front-desk requests. Your virtual receptionist follows your priorities and keeps outstanding items visible to the right team members.',path:'M9 3h6v4H9z M9 5H5v16h14V5h-4 M8 11l1 1 2-2 M13 11h3 M8 16l1 1 2-2 M13 16h3'},
 {title:'Physician Correspondence',text:'Capture messages accurately and route routine correspondence to the appropriate provider or staff member. Clear handoffs help your healthcare team stay informed while clinical questions reach licensed staff.',path:'M3 5h18v14H3z M3 6l9 7 9-7'}
 ];
 return <section className="reception-practice-support" aria-labelledby="reception-practice-support-title"><div className="reception-wrap"><div className="reception-practice-intro"><div><span className="reception-practice-label">Virtual Assistant Medical</span><h2 id="reception-practice-support-title">Six Ways VAM Keeps<br/><span>Your Practice Moving</span></h2></div><p>From the first patient call to the final administrative follow-up, coordinated remote support helps your team stay organized throughout the day.</p></div><div className="reception-practice-cards">{options.map((item,i)=><article key={item.title} className={'reception-practice-card reception-practice-tone-'+i}><span className="reception-practice-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round" strokeLinecap="round" aria-hidden="true"><path d={item.path}/></svg></span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
}
function ReceptionCommunication(){return <section className="reception-communication" aria-labelledby="reception-communication-title"><div className="reception-wrap"><h2 id="reception-communication-title">A Welcoming Voice.<br/><span>A More Connected Patient Experience.</span></h2><div className="reception-communication-grid"><div className="reception-communication-copy"><p>Every patient interaction starts with a conversation. Virtual Assistant Medical helps your practice make that first impression a positive one, with professional, thoughtful support for patient calls, appointment requests, and everyday enquiries.</p><p>Your virtual medical receptionist follows your call scripts, scheduling rules, and communication preferences. From confirming visits to routing messages to the right team member, VAM helps keep your front desk organized and your patients informed.</p><p>Support fits around your practice’s workflow, so your on-site team can give patients their attention while routine calls and follow-ups keep moving. Clinical questions are directed to your healthcare team.</p><a className="reception-button" href={contact}>Find Your Virtual Medical Receptionist</a></div><div className="reception-communication-art"><div className="reception-communication-portrait"><img src={communicationAssistant} alt="Friendly virtual receptionist wearing a headset" width="1024" height="1536" loading="lazy"/></div><div className="reception-communication-brand"><span className="brand-logo-crop"><img src={logo} alt="Virtual Assistant Medical"/></span></div><div className="reception-communication-card"><span className="reception-icon"><Icon kind={1}/></span><div><strong>Patient communication</strong><span>Calls · Appointments · Follow-ups</span></div></div></div></div></div></section>}
function ReceptionEHRSlider(){
 const logos=[{name:'athenahealth',file:'ehr-logo-6.png'},{name:'eClinicalWorks',file:'ehr-logo-1x.png'},{name:'MEDITECH',file:'ehr-logo-8.png'},{name:'Oracle Health',file:'ehr-logo-2.png'},{name:'Kareo',file:'ehr-logo-7.png'},{name:'Veradigm',file:'ehr-logo-4.png'},{name:'NextGen Healthcare',file:'ehr-logo-5.png'}];
 const [position,setPosition]=useState(0),[animate,setAnimate]=useState(true),[playing,setPlaying]=useState(true),[interacting,setInteracting]=useState(false);
 const touchStart=useRef<number|null>(null);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');if(media.matches)setPlaying(false);const listener=()=>{if(media.matches)setPlaying(false)};media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener)},[]);
 useEffect(()=>{if(!playing||interacting)return;const timer=window.setInterval(()=>setPosition(p=>p+1),3500);return()=>window.clearInterval(timer)},[playing,interacting]);
 useEffect(()=>{if(position!==logos.length)return;let frame=0;const timer=window.setTimeout(()=>{setAnimate(false);setPosition(0);frame=window.requestAnimationFrame(()=>{frame=window.requestAnimationFrame(()=>setAnimate(true))})},510);return()=>{window.clearTimeout(timer);window.cancelAnimationFrame(frame)}},[position]);
 function move(delta:number){setAnimate(true);setPosition(p=>delta<0?(p+logos.length-1)%logos.length:Math.min(p+1,logos.length))}
 return <section className="reception-ehr" id="reception-ehr" aria-labelledby="reception-ehr-title"><div className="reception-wrap"><h2 id="reception-ehr-title">Reception Support That Fits Your EHR</h2><p className="reception-ehr-copy">VAM can align reception tasks with your practice’s EHR workflow. Discuss your platform, permissions, and training needs during onboarding.</p><div className="reception-ehr-carousel" role="region" aria-roledescription="carousel" aria-label="EHR platforms" onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocus={()=>setInteracting(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setInteracting(false)}}><div className="reception-ehr-window" onTouchStart={e=>{touchStart.current=e.touches[0].clientX;setInteracting(true)}} onTouchEnd={e=>{if(touchStart.current!==null){const delta=e.changedTouches[0].clientX-touchStart.current;if(Math.abs(delta)>35)move(delta<0?1:-1)}touchStart.current=null;setInteracting(false)}}><ul className={`reception-ehr-track ${animate?'':'reception-ehr-instant'}`} style={{transform:`translateX(calc(-${position} * (100% / var(--ehr-visible))))`}}>{[...logos,...logos.slice(0,6)].map((logo,i)=><li key={i} aria-hidden={i>=logos.length?true:undefined}><img src={'/ehr/'+logo.file} alt={i>=logos.length?'':logo.name} width="230" height="100" loading="lazy"/></li>)}</ul></div><div className="reception-ehr-controls"><button className="reception-ehr-text-button" onClick={()=>move(-1)} aria-label="Previous EHR logo">Previous</button><div className="reception-ehr-dots" aria-label="Choose starting EHR logo">{logos.map((logo,i)=><button key={logo.name} className={position%logos.length===i?'active':''} aria-label={`Show ${logo.name}`} aria-pressed={position%logos.length===i} onClick={()=>{setAnimate(true);setPosition(i)}}/>)}</div><button className="reception-ehr-text-button" onClick={()=>move(1)} aria-label="Next EHR logo">Next</button><button className="reception-ehr-play" onClick={()=>setPlaying(p=>!p)} aria-label={playing?'Pause automatic sliding':'Play automatic sliding'}>{playing?'Pause':'Play'}</button></div></div></div></section>
}
function ReceptionHowItWorks(){
 const steps=[
 {title:'Hiring',label:'Find the right fit',text:'Tell VAM about your specialty, call volume, coverage hours, and front-desk priorities. Discuss suitable receptionist candidates and choose support that fits your practice.',path:'M8 10a3 3 0 1 0 0-6a3 3 0 1 0 0 6 M2 21v-3a6 6 0 0 1 12 0v3 M17 4a3 3 0 0 1 0 6 M18 15l2 2 3-4'},
 {title:'Onboarding',label:'Build around your workflow',text:'Set up approved system access, call scripts, scheduling rules, and message-routing procedures. Align responsibilities and escalation steps with your team before reception support begins.',path:'M3 4h18v13H3z M8 21h8 M12 17v4 M8 10l3 3 5-6'},
 {title:'Ongoing Support',label:'Keep improving together',text:'Review patient communication, appointment coordination, and everyday administrative tasks with VAM. Share feedback and adjust priorities as your practice’s needs change.',path:'M4 13v-2a8 8 0 0 1 16 0v2 M4 11H2v7h4v-7z M20 11h2v7h-4v-7z M20 18v2h-6 M10 20h4'}
 ];
 return <section className="reception-process" id="reception-how-it-works" aria-labelledby="reception-process-title"><div className="reception-wrap reception-process-layout"><div className="reception-process-intro"><span className="reception-process-label">Getting started with VAM</span><h2 id="reception-process-title">How It Works</h2><p>Bring a virtual medical receptionist into your practice in three clear steps.</p><a className="reception-button" href={contact}>Book a Consultation</a></div><ol className="reception-process-steps">{steps.map((step,i)=><li key={step.title} className={`reception-process-step reception-process-step-${i}`}><span className="reception-process-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={step.path}/></svg></span><div><span className="reception-process-step-label">{step.label}</span><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section>
}
function ReceptionSupportPanel({index}:{index:number}){
 const section=sections[index];const groups=index===11?[[1,2],[3,4]]:[[1],[2]];
 return <section id={index===12?'reception-contact':'reception-section-11'} className="reception-support-section"><div className="reception-wrap"><div className="reception-support-panel" style={{backgroundImage:`linear-gradient(105deg, rgba(12,35,69,.97), rgba(12,35,69,.83)), url(${doctor})`}}><div className="reception-support-heading"><h2>{section.title}</h2><p dangerouslySetInnerHTML={{__html:section.paragraphs[0]}}/></div><div className="reception-support-grid">{groups.map((group,i)=><div className="reception-support-card" key={i}><span className="reception-icon"><Icon kind={i===0?0:3}/></span><div>{group.map(n=><p key={n} dangerouslySetInnerHTML={{__html:section.paragraphs[n]}}/>)}</div></div>)}</div>{index===12&&<div className="reception-support-action"><div>{section.paragraphs.slice(3).map((p,i)=><p key={i} dangerouslySetInnerHTML={{__html:p}}/>)}</div><div className="reception-support-links"><a className="reception-button" href={contact}>Contact VAM Today</a><a className="reception-support-email" href="mailto:info@virtualassistantmedical.us">info@virtualassistantmedical.us</a></div></div>}</div></div></section>
}
export default function VirtualMedicalReceptionistPage(){
 useEffect(()=>{const tags=Array.from(document.querySelectorAll<HTMLMetaElement>('meta[name="robots"]'));const old=tags.map(t=>t.content);tags.forEach(t=>t.content='index, follow');return()=>tags.forEach((t,i)=>t.content=old[i])},[])
 return <main className="reception-page"><title>{RECEPTION_TITLE}</title><meta name="description" content={RECEPTION_DESCRIPTION}/><link rel="canonical" href={url}/><meta property="og:title" content={RECEPTION_TITLE}/><meta property="og:description" content={RECEPTION_DESCRIPTION}/><meta property="og:url" content={url}/><meta property="og:type" content="website"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <section className="reception-hero reception-hero-refined"><div className="reception-wrap reception-split"><div className="reception-hero-copy"><h1><span>Virtual Medical Receptionist</span> for Modern Healthcare Practices</h1><p>Virtual Assistant Medical helps your practice manage patient calls, appointment scheduling, reminders, and follow-ups with professional remote reception support—keeping your front desk organized and giving your team more time for patient care.</p><a className="reception-button" href="#reception-contact">Get Started With VAM</a></div><div className="reception-hero-art"><div className="reception-arch" aria-hidden="true"/><img src={portrait} alt="Virtual medical receptionist in teal scrubs wearing a headset" width="1024" height="1536" fetchPriority="high"/></div></div></section>
 {sections.slice(1).map((section,offset)=>{const n=offset+1;if(n===2)return <ReceptionOfficeSupport key={section.title}/>;if(n===3)return <section key={section.title} id="reception-section-3" className="reception-section reception-mint reception-patient-refresh"><div className="reception-wrap reception-split"><div><span className="reception-practice-label">Built around your patients</span><h2>{section.title}</h2><Paragraphs index={n}/><a className="reception-button" href="#reception-contact">Talk About Your Reception Needs</a></div><div className="reception-branded-photo"><img src="/images/reception-patient-service.webp" alt="VAM-branded medical receptionist wearing a headset and supporting patient calls at a laptop" loading="lazy" width="1200" height="900"/><div className="reception-photo-caption"><span className="reception-icon"><Icon kind={3}/></span><div><strong>A welcoming first point of contact</strong><span>Your call scripts. Your scheduling rules.</span></div></div></div></div></section>;if(n===11||n===12)return <Fragment key={section.title}><ReceptionSupportPanel index={n}/>{n===11&&<><ReceptionEHRSlider/><ReceptionHowItWorks/><ReceptionCommunication/></>}</Fragment>;return <Fragment key={section.title}><section id={n===12?'reception-contact':`reception-section-${n}`} className={`reception-section ${[3,6,8,10].includes(n)?'reception-mint':''} ${[5,11,12].includes(n)?'reception-navy':''}`}><div className="reception-wrap">
 {[1,4,9].includes(n)?<div className={`reception-split ${n===4?'reception-reverse':''} ${n===1?'reception-intro-refresh':''}`}><div><h2>{section.title}</h2><Paragraphs index={n}/>{n===1&&<a className="reception-button" href="#reception-contact">Get Reception Support</a>}</div><div className="reception-photo"><img src={n===9?doctor:n===1?assistant:"/images/reception-scheduling-new.webp"} alt={n===9?'Physician focusing on a patient during a consultation':n===1?'Receptionist with a headset working at a laptop in a bright medical office':'VAM-branded appointment scheduling assistant at a laptop with an appointment planner'} loading="lazy" width={n===9?1536:n===1?1254:1200} height={n===9?1024:n===1?1254:900}/></div></div>:<><div className="reception-heading">{[3,5,8].includes(n)&&<span className="reception-icon"><Icon kind={n===8?2:n===5?1:3}/></span>}<h2>{section.title}</h2></div><div className={n===12?'reception-cta-copy':'reception-copy'}><Paragraphs index={n}/></div></>}
 {section.items.length>0&&<ul className={`reception-items ${n===6?'reception-specialties':''}`}>{section.items.map((item,i)=><li key={item}><span className="reception-icon"><Icon kind={i}/></span><span>{item}</span></li>)}</ul>}
 {n===12&&<><a className="reception-button" href={contact}>Contact VAM Today</a><p className="reception-contact-line"><a href="mailto:info@virtualassistantmedical.us">info@virtualassistantmedical.us</a></p></>}
 </div></section>{n===1&&<ReceptionPracticeSupport/>}{n===9&&<ReceptionHighlights/>}</Fragment>})}
 <ServiceFAQs items={receptionistFAQs.map(([q,a])=>({q,a}))}/>
 </main>
}
