import './ServiceFAQs.css'
export type FAQ = {q:string;a:string}
export function sixServiceFAQs(items:FAQ[],title:string):FAQ[]{
 const extra:FAQ[]=[
 {q:`How does VAM tailor ${title.toLowerCase()} to my practice?`,a:'We review your priorities, existing systems, task volume, and internal procedures. Together, we define the responsibilities, communication preferences, and escalation rules for your remote support.'},
 {q:'How will we communicate and track tasks remotely?',a:'Agree on approved communication channels, task priorities, and update schedules with your team. Keep requests and progress in your practice’s chosen system so responsibilities and follow-ups are clear.'},
 {q:'How is patient information handled securely?',a:'Set role-based access, use approved secure communication tools, and limit information access to assigned responsibilities. Review applicable agreements, privacy procedures, and your practice’s requirements before sharing patient information.'},
 {q:'What determines the cost of support?',a:'Your task scope, coverage hours, and practice requirements determine the support you need. Contact VAM to discuss pricing and confirm the included services and terms before starting.'},
 {q:'How does onboarding work?',a:'Start by discussing your workflow and support needs with VAM. Your team then defines tasks, arranges appropriate system access, and shares procedures. The timeline depends on the scope and readiness of your practice.'},
 {q:'How can I review the quality of the support?',a:'Set clear expectations and review completed tasks, response times, and feedback with your support team. Regular check-ins help identify changes needed as your practice’s workload evolves.'}];
 return [...items,...extra].filter((x,i,all)=>all.findIndex(y=>y.q.toLowerCase()===x.q.toLowerCase())===i).slice(0,6)
}
export default function ServiceFAQs({items,id='service-faqs',schema=false,title='Frequently Asked Questions'}:{items:FAQ[];id?:string;schema?:boolean;title?:string}){return <section className="service-faq-section" id={id} aria-labelledby={id+'-heading'}><div className="service-faq-wrap"><div className="service-faq-eyebrow">Virtual Assistant Medical<span aria-hidden="true"/></div><h2 id={id+'-heading'}>{title}</h2><div className="service-faq-list">{items.map(({q,a})=><details key={q}><summary><span>{q}</span><span className="service-faq-toggle" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path d="m9 5 7 7-7 7"/></svg></span></summary><div className="service-faq-answer"><p>{a}</p></div></details>)}</div></div>{schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(({q,a})=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))})}}/>}</section>}
